/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waiteproj3;

import java.time.Instant;
import java.util.Date;

/**
 *
 * @author mw047
 */
public class BookStoreGUI extends javax.swing.JFrame {

    StoreItem[] inv = new StoreItem[20];
    int i = 0;  //inv index
    StoreItem x;
    String display = "Title" + String.format("%-25s", "     ") 
                + "Author" + String.format("%-25s", "     ") 
                + "Date Acquired" + String.format("%-25s", "     ") 
                + "Purchase Price" + String.format("%-25s", "     ") 
                + "Asking Price" + String.format("%-25s", "     ") 
                + "Genre" + String.format("%-25s", "     ")
                + "Director" + String.format("%-25s", "     ") 
                + "Actor" + String.format("%-25s", "     ") 
                + "Category" + String.format("%-25s", "     ") 
                + "Height" + String.format("%-25s", "     ") 
                + "Width" + String.format("%-25s", "     ") 
                + "Media" + String.format("%-25s", "     ") 
                + "\n"; 
    
    
    public void setFields(){

        inv[i].setAskingPrice(Integer.parseInt(aPriceTF.getText()));
        inv[i].setTitle(titleTF.getText());
        inv[i].setDateAcquired(aDatePicker.getDate());
        inv[i].setDateAcquired(rDatePicker.getDate());
        inv[i].setPurchasePrice(Integer.parseInt(pPriceTF.getText()));
        i++;
        setInvDisplay();
    }
    
    public void setInvDisplay(){
        for (int c=0; c<inv.length;c++) {
            if(c==i)
                break;
            else{
            display = display + inv[c].printableString();
            invDisplay.setText(display);}
        }
    }
    
    /**
     * Creates new form BookStoreGUI
     */
    public BookStoreGUI() {
        initComponents();
        invDisplay.setText(display);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invDisplay = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        InvIDTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RemoveB = new javax.swing.JButton();
        RemoveError = new javax.swing.JLabel();
        QuantityTF = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        genreTF = new javax.swing.JTextField();
        actorTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        authorL = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        directorTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        authorTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mediaTF = new javax.swing.JTextField();
        AddNew = new javax.swing.JButton();
        paintingRB = new javax.swing.JRadioButton();
        movieRB = new javax.swing.JRadioButton();
        bookRB = new javax.swing.JRadioButton();
        errorMessage = new javax.swing.JLabel();
        aDatePicker = new org.jdesktop.swingx.JXDatePicker();
        rDatePicker = new org.jdesktop.swingx.JXDatePicker();
        heightTF = new javax.swing.JFormattedTextField();
        widthTF = new javax.swing.JFormattedTextField();
        pPriceTF = new javax.swing.JTextField();
        aPriceTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invDisplay.setEditable(false);
        invDisplay.setColumns(20);
        invDisplay.setRows(5);
        invDisplay.setToolTipText("");
        invDisplay.setFocusable(false);
        invDisplay.setRequestFocusEnabled(false);
        invDisplay.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(invDisplay);

        jLabel1.setText("Inventory ID");

        jLabel2.setText("Quantity to Remove");

        RemoveB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RemoveB.setLabel("Remove");
        RemoveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBActionPerformed(evt);
            }
        });

        RemoveError.setForeground(new java.awt.Color(255, 0, 0));
        RemoveError.setToolTipText("");

        QuantityTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InvIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(RemoveB, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(RemoveError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(RemoveError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(RemoveB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        genreTF.setEnabled(false);

        actorTF.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Media");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Genre");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Width");

        authorL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        authorL.setText("Author");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Height");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Actor");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Purchase Price");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Title");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Release Date");

        directorTF.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Director");

        authorTF.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Asking Price");

        titleTF.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Date Acquired");

        mediaTF.setEnabled(false);
        mediaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaTFActionPerformed(evt);
            }
        });

        AddNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddNew.setText("Add New");
        AddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewActionPerformed(evt);
            }
        });

        buttonGroup1.add(paintingRB);
        paintingRB.setText("Painting");
        paintingRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(movieRB);
        movieRB.setText("Movie");
        movieRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(bookRB);
        bookRB.setText("Book");
        bookRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRBActionPerformed(evt);
            }
        });

        errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage.setToolTipText("");
        errorMessage.setFocusable(false);
        errorMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        errorMessage.setInheritsPopupMenu(false);
        errorMessage.setRequestFocusEnabled(false);
        errorMessage.setVerifyInputWhenFocusTarget(false);

        aDatePicker.setEnabled(false);

        rDatePicker.setEnabled(false);

        heightTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        heightTF.setEnabled(false);

        widthTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        widthTF.setEnabled(false);

        pPriceTF.setEnabled(false);

        aPriceTF.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookRB)
                                    .addComponent(movieRB)
                                    .addComponent(paintingRB))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(57, 57, 57)
                                                    .addComponent(jLabel9))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGap(72, 72, 72)
                                                    .addComponent(jLabel10))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(titleTF, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(authorL))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(genreTF, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6)))
                                    .addComponent(aDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(actorTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aPriceTF))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(authorTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                    .addComponent(pPriceTF))
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(7, 7, 7))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel14)
                                                            .addComponent(jLabel13))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(directorTF, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                                .addGap(92, 92, 92)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(heightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mediaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(widthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {actorTF, authorTF, directorTF, genreTF, mediaTF, titleTF});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(authorL)
                    .addComponent(authorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(mediaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(genreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(heightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(pPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(directorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(widthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(movieRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paintingRB)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(actorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(aPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(AddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {actorTF, authorTF, directorTF, genreTF, mediaTF, titleTF});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBActionPerformed
        try{
            //check for empty selection
            if(InvIDTF.getText().trim().isEmpty())
                throw new Exception();
            
            int e = Integer.parseInt(InvIDTF.getText());
            
            //check for invalid inventory selection
            if(e<0 || e>= inv.length)
                throw new Exception();
            
            //check for possible negative inventory attempt
            if(Integer.parseInt(QuantityTF.getText())> inv[e].getItemCount())
                throw new Exception();
            
            inv[e].remove(Integer.parseInt(QuantityTF.getText()));
            
        }
        catch(Exception ex){
            RemoveError.setText("ERROR! Invalid Operation.  Please Try again!");
        }
    }//GEN-LAST:event_RemoveBActionPerformed

    private void bookRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRBActionPerformed
        disableFields();
        genreTF.setEnabled(true);
        activateFields();
    }//GEN-LAST:event_bookRBActionPerformed

    private void movieRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieRBActionPerformed
        disableFields();
        genreTF.setEnabled(true);
        directorTF.setEnabled(true);
        actorTF.setEnabled(true);
        activateFields();
    }//GEN-LAST:event_movieRBActionPerformed

    private void paintingRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingRBActionPerformed
        disableFields();
        mediaTF.setEnabled(true);
        heightTF.setEnabled(true);
        widthTF.setEnabled(true);
        activateFields();
    }//GEN-LAST:event_paintingRBActionPerformed

    private void AddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewActionPerformed

        //check for errors
        //verify selection
        try{
            if(bookRB.isSelected()){
                x = new Book();
                ((Book)x).setGenre(genreTF.getText());     
            }
            else if(movieRB.isSelected()){
                x = new Movie();
                ((Movie)x).setDirector(directorTF.getText());
                ((Movie)x).setActor(actorTF.getText());
            }
            else if(paintingRB.isSelected()){
                x = new Painting();
                ((Painting)x).setHeight(Integer.parseInt(heightTF.getText()));
                ((Painting)x).setWidth(Integer.parseInt(widthTF.getText()));
                ((Painting)x).setMedia(mediaTF.getText());
            }
            else
            throw new Exception();
        }
        catch(Exception ex){
            errorMessage.setText("ERROR: No category selected!");
        }
        //verify dates
        try{
            if (rDatePicker.getDate().after(aDatePicker.getDate()))
                throw new Exception();
            if (rDatePicker.getDate().after(Date.from(Instant.now())))
                throw new Exception();
            if (aDatePicker.getDate().after(Date.from(Instant.now())))
                throw new Exception();
        }
        catch(Exception ex){
            errorMessage.setText("ERROR: Invalid Dates!");
        }
        //verify text input
        try{
            if(genreTF.isEnabled()&& genreTF.getText().trim().isEmpty())
                throw new Exception();
            if(directorTF.isEnabled()&& directorTF.getText().trim().isEmpty())
                throw new Exception();
            if(actorTF.isEnabled()&& actorTF.getText().trim().isEmpty())
                throw new Exception();
            if(mediaTF.isEnabled()&& mediaTF.getText().trim().isEmpty())
                throw new Exception();
            if(heightTF.isEnabled()&& heightTF.getText().trim().isEmpty())
                throw new Exception();
            if(widthTF.isEnabled()&& widthTF.getText().trim().isEmpty())
                throw new Exception();
            if(aPriceTF.getText().trim().isEmpty())
                throw new Exception();
            if(titleTF.getText().trim().isEmpty())
                throw new Exception();
            if(pPriceTF.getText().trim().isEmpty())
                throw new Exception();
        }
        catch(Exception ex)
        {
            errorMessage.setText("ERROR: Please fill in all required fields");
        }
        inv[i]=x;
        setFields();
    }//GEN-LAST:event_AddNewActionPerformed

    private void mediaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediaTFActionPerformed

    private void disableFields() {
        genreTF.setEnabled(false);
        directorTF.setEnabled(false);
        actorTF.setEnabled(false);
        mediaTF.setEnabled(false);
        heightTF.setEnabled(false);
        widthTF.setEnabled(false);
    }

    private void activateFields() {
        rDatePicker.setEnabled(true);
        aPriceTF.setEnabled(true);
        pPriceTF.setEnabled(true);
        titleTF.setEnabled(true);
        aDatePicker.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookStoreGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNew;
    private javax.swing.JTextField InvIDTF;
    private javax.swing.JFormattedTextField QuantityTF;
    private javax.swing.JButton RemoveB;
    private javax.swing.JLabel RemoveError;
    private org.jdesktop.swingx.JXDatePicker aDatePicker;
    private javax.swing.JTextField aPriceTF;
    private javax.swing.JTextField actorTF;
    private javax.swing.JLabel authorL;
    private javax.swing.JTextField authorTF;
    private javax.swing.JRadioButton bookRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField directorTF;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JTextField genreTF;
    private javax.swing.JFormattedTextField heightTF;
    private javax.swing.JTextArea invDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mediaTF;
    private javax.swing.JRadioButton movieRB;
    private javax.swing.JTextField pPriceTF;
    private javax.swing.JRadioButton paintingRB;
    private org.jdesktop.swingx.JXDatePicker rDatePicker;
    private javax.swing.JTextField titleTF;
    private javax.swing.JFormattedTextField widthTF;
    // End of variables declaration//GEN-END:variables

}
